#!/bin/bash -e

source "$(dirname "$(dirname "$0")")/bin/env"

service_name="nginx-ingress-controller"
dnsprovider="$(getconfig dns.type)"

info "Removing DNS record ..."

(
  cd "$GEN/$service_name"
  terraform init "$CURRENT/dns/$dnsprovider"
  terraform destroy -var-file="$GEN/$service_name/terraform.tfvars" -state="$STATE/$service_name-dns.tfstate" "$CURRENT"/dns/$dnsprovider
)